<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b31382d8-c044-4477-844d-4cf0ae7025c7</elementGuidId>
    <imagePath></imagePath>
    <name>link_time</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/aside[1]/nav[1]/div[2]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/web/index.php/time/viewTimeModule') and equals(@text,'Time')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="Time"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/web/index.php/time/viewTimeModule</value>
        <webElementGuid>e4290a7e-d5ed-48dd-b83c-5a14427fd03b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Time</value>
        <webElementGuid>e4290a7e-d5ed-48dd-b83c-5a14427fd03b</webElementGuid>
    </webElementProperties>
</WebElementEntity>